#!/bin/bash

set -e

echo "Installing auto_init labextension..."
cd /srv/conda/envs/notebook/share/jupyter/labextensions
mv $HOME/auto_init ./auto_init
echo "Done"

echo "Installing hide_code labextension..."
mv $HOME/hide_code .
echo "Done"

echo "Setting up default settings overrides..."
cd ..
mkdir lab/settings
mv $HOME/overrides.json lab/settings/

echo "Done"
