#!/bin/bash

set -e

echo "Installing auto_init labextension..."
cd /srv/conda/envs/notebook/share/jupyter/labextensions
mv $HOME/auto_init ./auto_init
echo "Done"
echo "Installing hide_code labextension..."
mv $HOME/hide_code .
echo "Done"
