name: Build Notebook Container
on: [push]

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: soralsei
        DOCKER_PASSWORD: dckr_pat_t1JLODwu5MhofSyMrZb-7_WnPDw
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
        IMAGE_NAME: soralsei/jupyter_generic_sleep_analysis
